// src/routes/index.svelte
<script lang="ts">
   import { defaultBackground } from '$lib/global-store';
   defaultBackground();
</script>

<head>
   <title>ScoreSaber!</title>
</head>

<div>
   <section class="section is-fullwidth no-padding">
      <div>
         <section class="hero is-custom is-banner is-bold" style="background-image: url('/images/banner.jpg');">
            <div class="hero-body" />
         </section>
      </div>
   </section>
   <div class="section breakout">
      <div class="window has-shadow">
         <h3>Welcome to ScoreSaber</h3>
         <p>
            ScoreSaber is Beat Sabers largest leaderboard system for custom songs, hosting 60 million scores across 170,000+ leaderboards, with more
            than 1 million users worldwide
         </p>
      </div>
   </div>
</div>

<style>
   @media screen and (min-width: 769px), print {
      .hero.is-custom .hero-body {
         height: 20vw;
         min-height: 10rem;
         width: 100%;
         background-repeat: no-repeat;
      }
   }
   .hero.is-banner {
      background-image: url('../images/banner.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center center;
      box-shadow: 0 4px 10px 0 rgba(0, 0, 0, 0.21) !important;
   }
   .section.is-fullwidth.no-padding {
      padding-top: 0px;
      padding-bottom: 0px;
      padding-right: 0px;
      padding-left: 0px;
      width: 100vw;
      margin-left: 50%;
      transform: translateX(-50%);
   }
</style>

// src/routes/index.tsx
import { Helmet } from 'react-helmet-async';
import Navbar from '../components/navbar';

export default function Index() {
   return (
      <div>
         <Navbar />
         <Helmet>
            <title>ScoreSaber!</title>
         </Helmet>
         <section className="section is-fullwidth no-padding">
            <div className="bd-example">
               <section className="hero is-custom is-banner is-bold">
                  <div className="hero-body">
                     <div className="container">
                        <div className="columns is-mobile is-centered">
                           <div className="column is-half"></div>
                        </div>
                     </div>
                  </div>
               </section>
            </div>
         </section>

         <div className="section">
            <div className="container">
               <div className="content">
                  <div className="columns">
                     <div className="column">
                        <div className="box has-shadow">
                           <h3>Welcome to ScoreSaber</h3>
                           <p>
                              ScoreSaber is Beat Sabers largest leaderboard system for custom songs, hosting 60 million scores across 170,000+ leaderboards, with more than 1
                              million users worldwide
                           </p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   );
}
