// src/routes/rankings.tsx
import { Helmet } from 'react-helmet-async';
import Navbar from '../components/navbar';
import queryString from 'query-string';
import fetch from '../utils/fetcher';
import useSWR from 'swr';
import { Player } from '../entities/PlayerData';
import BeatLoader from 'react-spinners/BeatLoader';
import Error from '../components/error';
import ArrowPagination from '../components/arrow-pagination';
import RankingPlayerItem from '../components/rankings/player-item';
import { useHistory, useLocation } from 'react-router-dom';

interface PageRequestParams {
   search?: string;
   countries?: string;
   page: number | undefined;
}

export default function Rankings() {
   const history = useHistory();
   const parsed = queryString.parse(useLocation().search);
   const requestParams: PageRequestParams = parsed as unknown as PageRequestParams; // Cause queryString.parse<PageRequestParams> doesn't exist (╯°□°）╯︵ ┻━┻)
   const playersPerPage = 50;

   const { data: rankings, error: rankingsError } = useSWR<Player[]>(queryString.stringifyUrl({ url: '/api/players', query: parsed }), fetch);
   const { data: playerCount, error: playerCountError } = useSWR<number>(queryString.stringifyUrl({ url: '/api/players/count', query: parsed }), fetch);

   const changePage = (page: number) => {
      requestParams.page = page;
      updateUrl(requestParams);
   };

   const handleSearch = (searchTerm: string) => {
      if (searchTerm === '') {
         requestParams.search = undefined;
         changePage(1);
      } else {
         requestParams.search = searchTerm;
         requestParams.page = undefined;
         updateUrl(requestParams);
      }
   };

   const updateUrl = (pageRequestParams: PageRequestParams) => {
      history.push(`/rankings?${queryString.stringify(pageRequestParams)}`);
   };

   return (
      <div>
         <Navbar searchCallback={handleSearch} />
         <Helmet>
            <title>Global Rankings | ScoreSaber!</title>
         </Helmet>
         <div className="section">
            <div className="container">
               <div className="content">
                  <div className="columns is-desktop is-flex-reverse">
                     <div className="column is-one-quarter-desktop">
                        <h4 className="title is-4">Details:</h4>
                        <div className="box has-shadow">
                           <p>Earn global rankings simply by playing ranked maps!</p>
                           <p>
                              Each <strong>ranked</strong> song on ScoreSaber has a hidden difficulty value attached to it determined by the PP algorithm.
                           </p>
                        </div>
                     </div>
                     <div className="column">
                        <h4 className="title is-4">Player Rankings:</h4>
                        <div className="box has-shadow">
                           {rankingsError && <Error message={rankingsError.message} />}
                           {rankings && playerCount && !rankingsError && !playerCountError ? (
                              <div>
                                 <ArrowPagination page={requestParams.page} callback={changePage} maxPages={Math.ceil(playerCount / playersPerPage)} />
                                 <div className="ranking global">
                                    <table className="ranking global">
                                       <thead>
                                          <tr>
                                             <th className="picture" />
                                             <th className="rank">Rank</th>
                                             <th className="player">Player</th>
                                             <th className="pp">Performance Points</th>
                                             <th className="difference">Weekly Change</th>
                                          </tr>
                                       </thead>
                                       <tbody>
                                          {rankings &&
                                             rankings.map((player) => {
                                                return <RankingPlayerItem key={player.id} player={player} />;
                                             })}
                                       </tbody>
                                    </table>
                                 </div>
                                 <ArrowPagination page={requestParams.page} callback={changePage} maxPages={Math.ceil(playerCount / playersPerPage)} />
                              </div>
                           ) : (
                              <div className="sweet-loading is-center">
                                 <BeatLoader size={15} color={'#22A7F2'} loading={!rankingsError} />
                              </div>
                           )}
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   );
}

// src/routes/rankings.svelte
<script lang="ts">
   import type { Player } from '$lib/models/PlayerData';
   import Navbar from '$lib/components/common/navbar.svelte';
   import Footer from '$lib/components/common/footer.svelte';
   import Loader from '$lib/components/common/loader.svelte';
   import Error from '$lib/components/common/error.svelte';
   import PlayerRow from '$lib/components/player/player-row.svelte';
   import ArrowPagination from '$lib/components/common/arrow-pagination.svelte';
   import axios from '$lib/utils/fetcher';
   import queryString from 'query-string';
   import { useAccio } from '$lib/utils/accio';
   import { createQueryStore } from '$lib/query-store';
   import { page } from '$app/stores';
   import { fly } from 'svelte/transition';

   const playersPerPage = 50;

   $: currentPage = createQueryStore('page', 1, queryChanged);

   const {
      data: rankings,
      error: rankingsError,
      refresh: refreshRankings
   } = useAccio<Player[]>(
      queryString.stringifyUrl({
         url: '/api/players',
         query: queryString.parse($page.query.toString())
      }),
      { fetcher: axios }
   );

   const {
      data: playerCount,
      error: playerCountError,
      refresh: refreshPlayerCount //TODO: Refresh on filter change (not page change)
   } = useAccio<number>(
      queryString.stringifyUrl({
         url: '/api/players/count',
         query: queryString.parse($page.query.toString())
      }),
      { fetcher: axios }
   );

   function changePage(newPage: number) {
      $currentPage = newPage;
   }

   function queryChanged(newQuery: string) {
      refreshRankings({ query: newQuery });
   }
</script>

<head>
   <title>Rankings | ScoreSaber!</title>
</head>

<Navbar />

<div class="section">
   <div class="window has-shadow noheading">
      {#if $playerCount}
         <ArrowPagination pageClicked={changePage} page={parseInt($currentPage)} maxPages={Math.ceil($playerCount / playersPerPage)} />
      {/if}
      {#if $rankings && $playerCount}
         <div in:fly={{ y: -20, duration: 1000 }} class="ranking">
            <table>
               <thead>
                  <tr class="headers">
                     <th class="rank" />
                     <th class="player" />
                     <th class="pp centered">Performance Points</th>
                     <th class="total-play-count centered">Total Play Count</th>
                     <th class="ranked-play-count centered">Ranked Play Count</th>
                     <th class="ranked-acc centered">Average Ranked Accuracy</th>
                     <th class="difference centered">Weekly Change</th>
                  </tr>
               </thead>
               <tbody>
                  {#each $rankings as player}
                     <PlayerRow {player} />
                  {/each}
               </tbody>
            </table>
         </div>
         <br />
      {:else if !$rankingsError && !$playerCountError}
         <Loader />
      {/if}
      {#if $rankingsError || $playerCountError}
         <Error message={$rankingsError.toString() || $playerCountError.toString()} />
      {/if}
      {#if $playerCount}
         <ArrowPagination pageClicked={changePage} page={parseInt($currentPage)} maxPages={Math.ceil($playerCount / playersPerPage)} />
      {/if}
   </div>
</div>

<Footer />

<style>
   table {
      border-collapse: separate;
      white-space: nowrap;
      border-spacing: 0 5px;
   }
   div.ranking {
      overflow-x: auto;
   }
   .content table th {
      border: none !important;
   }

   @media (max-width: 512px) {
      .headers {
         display: none;
      }

      .headers th:not(.player, .rank) {
         display: none;
      }
   }
</style>
