// src/routes/team.svelte
<script lang="ts">
   import type { ScoreSaberTeam } from '$lib/models/ScoreSaberTeam';
   import axios from '$lib/utils/fetcher';
   import Navbar from '$lib/components/common/navbar.svelte';
   import Footer from '$lib/components/common/footer.svelte';
   import TeamItem from '$lib/components/team/team-item.svelte';
   import Loader from '$lib/components/common/loader.svelte';
   import { useAccio } from '$lib/utils/accio';

   const { data: team, error } = useAccio<ScoreSaberTeam>('https://raw.githubusercontent.com/Umbranoxio/ScoreSaber-Team/main/team.json', {
      fetcher: axios
   });
</script>

<head>
   <title>Team | ScoreSaber!</title>
</head>

<Navbar />

<div class="section">
   <div class="window has-shadow">
      {#if $team}
         <h1 class="title is-4">The ScoreSaber Team</h1>
         <div>
            <TeamItem title="Creator & Project Lead" teamMembers={$team.TeamMembers.Backend} />
            <TeamItem title="Admin" teamMembers={$team.TeamMembers.Admin} removeUmbra={true} />
            <TeamItem title="Nomination Assesment Team" teamMembers={$team.TeamMembers.NAT} />
            <TeamItem title="Ranking Team" teamMembers={$team.TeamMembers.RT} />
            <TeamItem title="Quality Assurance Team" teamMembers={$team.TeamMembers.QAT} />
            <TeamItem title="Criteria Assesment Team" teamMembers={$team.TeamMembers.CAT} />
            <TeamItem title="PC Mod" teamMembers={$team.TeamMembers.Mod} />
            <TeamItem title="PPv3" teamMembers={$team.TeamMembers.PPv3} removeUmbra={true} />
         </div>
      {:else if !$error}
         <Loader />
      {/if}
      {#if $error}
         <p>{$error}</p>
      {/if}
   </div>
</div>

<Footer />

<style>
</style>

// src/routes/team.tsx
import { Helmet } from 'react-helmet-async';
import Navbar from '../components/navbar';
import { ScoreSaberTeam } from '../models/ScoreSaberTeam';
import fetch from '../utils/fetcher';
import useSWR from 'swr';
import TeamItem from '../components/team/team-item';
import BeatLoader from 'react-spinners/BeatLoader';

export default function Team() {
   const { data: team } = useSWR<ScoreSaberTeam>('https://raw.githubusercontent.com/Umbranoxio/ScoreSaber-Team/main/team.json', fetch);
   return (
      <div>
         <Navbar />
         <Helmet>
            <title>ScoreSaber Team!</title>
         </Helmet>
         <div className="section">
            <div className="container">
               <div className="box has-shadow">
                  <h1 className="title is-4">The ScoreSaber Team</h1>
                  {team ? (
                     <div>
                        <TeamItem title={'Creator & Project Lead'} teamMembers={team.TeamMembers.Backend} />
                        <TeamItem title={'Admin'} teamMembers={team.TeamMembers.Admin} removeUmbra={true} />
                        <TeamItem title={'Nomination Assesment Team'} teamMembers={team.TeamMembers.NAT} />
                        <TeamItem title={'Ranking Team'} teamMembers={team.TeamMembers.RT} />
                        <TeamItem title={'Quality Assurance Team'} teamMembers={team.TeamMembers.QAT} />
                        <TeamItem title={'Criteria Assesment Team'} teamMembers={team.TeamMembers.CAT} />
                        <TeamItem title={'PC Mod'} teamMembers={team.TeamMembers.Mod} />
                        <TeamItem title={'PPv3'} teamMembers={team.TeamMembers.PPv3} removeUmbra={true} />
                     </div>
                  ) : (
                     <div className="sweet-loading is-center">
                        <BeatLoader size={15} color={'#22A7F2'} loading={team} />
                     </div>
                  )}
               </div>
            </div>
         </div>
      </div>
   );
}
