// src/lib/components/image/country-image.svelte
<script lang="ts">
   import { getName } from 'country-list';

   import { getCDNUrl } from '$lib/utils/helpers';

   export let country: string;

   $: countryImage = getCDNUrl('/flags/unknown.png');
   $: countryEmoji = 'Unknown';

   $: {
      if (country != '') {
         const toTwemojiFlag = (input: string) =>
            `https://twemoji.maxcdn.com/v/13.1.0/svg/${input
               .toLowerCase()
               .match(/[a-z]/g)
               .map((i) => (i.codePointAt(0) + 127365).toString(16))
               .join('-')}.svg`;
         const toEmojiFlag = (countryCode: string): string =>
            countryCode.toLowerCase().replace(/[a-z]/g, (i) => String.fromCodePoint((i.codePointAt(0) ?? 0) - 97 + 0x1f1e6));

         countryImage = toTwemojiFlag(country);
         countryEmoji = toEmojiFlag(country);
      }
   }
</script>

<img alt={countryEmoji} title={getName(country)} src={countryImage} class="country" />

<style>
   .country {
      cursor: help;
      width: 18px;
      height: 18px;
      display: inline-block;
      vertical-align: sub;
   }
</style>

// src/shared/components/country-image.tsx
'use client';

import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';

import { FadeInImage } from '@/shared/components/fade-in-image';
import { getCountryName } from '@/shared/country-region/countries';
import { cn } from '@/shared/format/helpers';

interface CountryImageProps {
   country: string;
   className?: string;
   size?: number;
}

export function CountryImage({ country, className, size = 24 }: CountryImageProps) {
   const countryImage = generateFlagUrl(country);
   const countryEmoji = generateFlagEmoji(country);
   const countryName = getCountryName(country);

   return (
      <Tooltip>
         <TooltipTrigger asChild>
            <div className={cn('flex cursor-help items-center', className)}>
               <FadeInImage className="max-w-none" alt={countryEmoji} src={countryImage} width={size} height={size} />
            </div>
         </TooltipTrigger>
         <TooltipContent>
            <p>{countryName}</p>
         </TooltipContent>
      </Tooltip>
   );
}

// local twemoji flag path
function generateFlagUrl(countryCode: string) {
   const matches = countryCode.toLowerCase().match(/[a-z]/g);
   if (!matches) return '/twemoji/unknown.png';

   return `/twemoji/${matches
      .map((char) => {
         const codePoint = char.codePointAt(0);
         return codePoint ? (codePoint + 127365).toString(16) : '';
      })
      .join('-')}.png`;
}

// flag emoji for alt text
function generateFlagEmoji(countryCode: string) {
   return countryCode.toLowerCase().replace(/[a-z]/g, (char) => {
      const codePoint = char.codePointAt(0);
      return codePoint ? String.fromCodePoint(codePoint - 97 + 0x1f1e6) : '';
   });
}

export { generateFlagUrl };
