// src/components/team/team-item.tsx
import { TeamMember } from '../../models/ScoreSaberTeam';
import TeamMemberItem from './team-member-item';

export type TeamItemProperties = {
   title: string;
   teamMembers: TeamMember[];
   removeUmbra?: boolean;
};

export default function TeamHeader(properties: TeamItemProperties) {
   const { title, teamMembers, removeUmbra } = properties;
   return (
      <div className="team-panel">
         <h2 className="title is-5">{title}</h2>
         <div className="columns is-multiline">
            {teamMembers &&
               teamMembers.map((member) => {
                  if (removeUmbra && member.Name === 'Umbranox') {
                     return null;
                  } else {
                     return <TeamMemberItem key={member.Name} teamMember={member} />;
                  }
               })}
         </div>
      </div>
   );
}

// src/lib/components/team/team-item.svelte
<script lang="ts">
   import type { TeamMember } from '$lib/models/ScoreSaberTeam';
   import TeamMemberItem from '$lib/components/team/team-member-item.svelte';
   export let title: string;
   export let teamMembers: TeamMember[];
   export let removeUmbra: boolean = false;
</script>

<div class="team-panel">
   <h2 class="title is-5">{title}</h2>
   <div class="columns is-multiline">
      {#each teamMembers as teamMember}
         {#if removeUmbra && teamMember.Name === 'Umbranox'}{:else}
            <TeamMemberItem {teamMember} />
         {/if}
      {/each}
   </div>
</div>

<style>
   div.team-panel {
      margin-bottom: 20px;
   }
</style>
