// src/lib/components/common/arrow-pagination.svelte
<script lang="ts" context="module">
   export interface PageCallback {
      (page: number): void;
   }
</script>

<script lang="ts">
   export let page: number;
   export let maxPages: number;
   export let pageClicked: PageCallback;
</script>

<nav class="pagination">
   {#if page > 1}
      <button on:click={() => pageClicked(page - 1)} class="button arrow">
         <span class="icon is-small">
            <i class="fas fa-arrow-left" />
         </span>
      </button>
   {:else}
      <button class="button arrow" disabled>
         <span class="icon is-small">
            <i class="fas fa-arrow-left" />
         </span>
      </button>
   {/if}
   {#if page < maxPages}
      <button on:click={() => pageClicked(page + 1)} class="button arrow">
         <span class="icon is-small">
            <i class="fas fa-arrow-right" />
         </span>
      </button>
   {:else}
      <button class="button arrow" disabled>
         <span class="icon is-small">
            <i class="fas fa-arrow-right" />
         </span>
      </button>
   {/if}
</nav>

<style>
   .pagination .button {
      background-color: #2d2d2d !important;
      border-color: var(--foreground) !important;
      color: var(--alternate) !important;
      display: flex;
   }
   .pagination .button:hover {
      color: var(--scoreSaberYellow) !important;
   }
</style>

// src/components/arrow-pagination.tsx
type PaginationProperties = {
	page: number;
	maxPages: number;
	callback: PageClickCallback;
};

export interface PageClickCallback {
	(page: number): void;
}

export default function ArrowPagination(properties: PaginationProperties) {
	return (
		<nav className="pagination">
			{properties.page <= 1 && <br />}
			{properties.page > 1 && (
				<button onClick={() => properties.callback(properties.page - 1)} className="button arrow">
					<span className="icon is-small">
						<i className="fas fa-arrow-left" />
					</span>
				</button>
			)}
			{properties.page < properties.maxPages && (
				<button onClick={() => properties.callback(properties.page + 1)} className="button arrow">
					<span className="icon is-small">
						<i className="fas fa-arrow-right" />
					</span>
				</button>
			)}
		</nav>
	);
}
